-- =============================================================================
-- V1__create_bookings_table.sql
-- FreightFlow Booking Service — Initial schema for the bookings table.
--
-- Creates the core bookings table with all columns required by the Booking
-- aggregate root, including cargo details, lifecycle state, voyage assignment,
-- and audit/versioning columns.
-- =============================================================================

-- ---------------------------------------------------------------------------
-- Bookings table — stores the Booking aggregate root
-- ---------------------------------------------------------------------------
CREATE TABLE bookings (
    -- Primary key: UUID generated by the application (domain-driven ID)
    id                       UUID            PRIMARY KEY,

    -- Customer who placed the booking
    customer_id              UUID            NOT NULL,

    -- Booking lifecycle status (DRAFT, CONFIRMED, SHIPPED, DELIVERED, CANCELLED)
    status                   VARCHAR(20)     NOT NULL,

    -- Cargo details (embedded value object)
    commodity_code           VARCHAR(20)     NOT NULL,
    description              VARCHAR(500)    NOT NULL,
    weight_value             NUMERIC(12, 4)  NOT NULL,
    weight_unit              VARCHAR(5)      NOT NULL DEFAULT 'KG',
    container_type           VARCHAR(20)     NOT NULL,
    container_count          INTEGER         NOT NULL CHECK (container_count > 0),

    -- Route: origin and destination port codes (UN/LOCODE)
    origin_port              VARCHAR(10)     NOT NULL,
    destination_port         VARCHAR(10)     NOT NULL,

    -- Voyage assignment (populated on confirmation)
    voyage_id                UUID,

    -- Cancellation details (populated on cancellation)
    cancellation_reason      VARCHAR(1000),

    -- Requested departure date
    requested_departure_date DATE            NOT NULL,

    -- Audit columns
    created_at               TIMESTAMPTZ     NOT NULL DEFAULT NOW(),
    updated_at               TIMESTAMPTZ     NOT NULL DEFAULT NOW(),

    -- Optimistic locking version
    version                  BIGINT          NOT NULL DEFAULT 0
);

-- ---------------------------------------------------------------------------
-- Indexes for common query patterns
-- ---------------------------------------------------------------------------

-- Customer bookings lookup (used by getBookingsByCustomer)
CREATE INDEX idx_bookings_customer_id ON bookings (customer_id);

-- Status-based queries (e.g., find all DRAFT bookings for batch processing)
CREATE INDEX idx_bookings_status ON bookings (status);

-- Time-based queries and ordering (e.g., recent bookings dashboard)
CREATE INDEX idx_bookings_created_at ON bookings (created_at);

-- Composite index for customer + status queries
CREATE INDEX idx_bookings_customer_status ON bookings (customer_id, status);

-- ---------------------------------------------------------------------------
-- Comments for documentation
-- ---------------------------------------------------------------------------
COMMENT ON TABLE bookings IS 'Booking aggregate root — manages the full lifecycle of a freight booking.';
COMMENT ON COLUMN bookings.id IS 'Domain-generated UUID serving as the aggregate identity.';
COMMENT ON COLUMN bookings.customer_id IS 'UUID of the customer who owns this booking.';
COMMENT ON COLUMN bookings.status IS 'Current lifecycle state: DRAFT, CONFIRMED, SHIPPED, DELIVERED, or CANCELLED.';
COMMENT ON COLUMN bookings.commodity_code IS 'HS (Harmonized System) commodity classification code.';
COMMENT ON COLUMN bookings.description IS 'Human-readable description of the cargo contents.';
COMMENT ON COLUMN bookings.weight_value IS 'Numeric weight value of the cargo.';
COMMENT ON COLUMN bookings.weight_unit IS 'Unit of measurement for weight (KG or LBS).';
COMMENT ON COLUMN bookings.container_type IS 'Container type: DRY_20, DRY_40, REEFER_20, REEFER_40, HIGH_CUBE_40, OPEN_TOP_20.';
COMMENT ON COLUMN bookings.container_count IS 'Number of containers required (must be positive).';
COMMENT ON COLUMN bookings.origin_port IS 'Origin port UN/LOCODE (e.g., CNSHA for Shanghai).';
COMMENT ON COLUMN bookings.destination_port IS 'Destination port UN/LOCODE (e.g., USLAX for Los Angeles).';
COMMENT ON COLUMN bookings.voyage_id IS 'Assigned voyage UUID — populated when booking is confirmed.';
COMMENT ON COLUMN bookings.cancellation_reason IS 'Reason for cancellation — populated when booking is cancelled.';
COMMENT ON COLUMN bookings.requested_departure_date IS 'Customer-requested departure date.';
COMMENT ON COLUMN bookings.created_at IS 'Timestamp when the booking was created (with timezone).';
COMMENT ON COLUMN bookings.updated_at IS 'Timestamp of the last modification (with timezone).';
COMMENT ON COLUMN bookings.version IS 'Optimistic locking version — incremented on each update.';
