-- =============================================================================
-- V4__create_outbox_table.sql
-- FreightFlow Booking Service — Transactional Outbox table for reliable
-- event publishing using the Outbox Pattern.
--
-- Events are written to this table in the SAME transaction as the aggregate
-- state change, eliminating dual-write inconsistency. A separate polling
-- processor reads unprocessed events and forwards them to Kafka.
-- =============================================================================

CREATE TABLE outbox_events (
    -- Primary key: UUID generated by PostgreSQL
    id              UUID            PRIMARY KEY DEFAULT gen_random_uuid(),

    -- Aggregate identification (for routing and partitioning)
    aggregate_type  VARCHAR(100)    NOT NULL,
    aggregate_id    UUID            NOT NULL,

    -- Event metadata
    event_type      VARCHAR(100)    NOT NULL,
    payload         JSONB           NOT NULL,
    metadata        JSONB,

    -- Lifecycle timestamps
    created_at      TIMESTAMPTZ     NOT NULL DEFAULT NOW(),
    processed       BOOLEAN         NOT NULL DEFAULT FALSE,
    processed_at    TIMESTAMPTZ
);

-- Index for the polling processor: efficiently find unprocessed events in order
CREATE INDEX idx_outbox_unprocessed ON outbox_events (created_at) WHERE processed = FALSE;

-- Index for aggregate-based lookups (debugging, replay)
CREATE INDEX idx_outbox_aggregate ON outbox_events (aggregate_id, aggregate_type);

-- ---------------------------------------------------------------------------
-- Comments for documentation
-- ---------------------------------------------------------------------------
COMMENT ON TABLE outbox_events IS 'Transactional outbox for reliable event publishing (Outbox Pattern).';
COMMENT ON COLUMN outbox_events.aggregate_type IS 'The type of aggregate that produced this event (e.g., Booking).';
COMMENT ON COLUMN outbox_events.aggregate_id IS 'The aggregate root ID that produced this event.';
COMMENT ON COLUMN outbox_events.event_type IS 'The domain event type name (e.g., BookingCreated).';
COMMENT ON COLUMN outbox_events.payload IS 'The serialized event payload as JSON.';
COMMENT ON COLUMN outbox_events.metadata IS 'Optional metadata: correlationId, causationId, timestamp.';
COMMENT ON COLUMN outbox_events.processed IS 'Whether this event has been successfully forwarded to the message broker.';
COMMENT ON COLUMN outbox_events.processed_at IS 'Timestamp when this event was successfully forwarded.';
