-- =============================================================================
-- V1__create_billing_tables.sql
-- FreightFlow Billing Service — Initial schema for billing.
--
-- Creates the invoices, line_items, payments, and ledger_entries tables.
-- =============================================================================

-- ---------------------------------------------------------------------------
-- Invoices table — stores the Invoice aggregate root
-- ---------------------------------------------------------------------------
CREATE TABLE invoices (
    -- Primary key: UUID generated by the application
    id                       UUID            PRIMARY KEY,

    -- Booking this invoice is for
    booking_id               UUID            NOT NULL,

    -- Customer being invoiced
    customer_id              UUID            NOT NULL,

    -- Invoice lifecycle status (DRAFT, ISSUED, PAID, OVERDUE, CANCELLED)
    status                   VARCHAR(20)     NOT NULL,

    -- Financial details
    total_amount             NUMERIC(14, 2)  NOT NULL DEFAULT 0,
    currency                 VARCHAR(3)      NOT NULL DEFAULT 'USD',
    due_date                 DATE            NOT NULL,

    -- Payment details (populated when payment is recorded)
    payment_id               UUID,
    payment_amount           NUMERIC(14, 2),
    payment_method           VARCHAR(20),
    paid_at                  TIMESTAMPTZ,
    payment_reference        VARCHAR(100),

    -- Cancellation details
    cancellation_reason      VARCHAR(1000),

    -- Audit columns
    created_at               TIMESTAMPTZ     NOT NULL DEFAULT NOW(),
    updated_at               TIMESTAMPTZ     NOT NULL DEFAULT NOW(),

    -- Optimistic locking version
    version                  BIGINT          NOT NULL DEFAULT 0
);

-- ---------------------------------------------------------------------------
-- Line Items table — stores individual charges on an invoice
-- ---------------------------------------------------------------------------
CREATE TABLE line_items (
    id                       UUID            PRIMARY KEY DEFAULT gen_random_uuid(),

    -- Reference to invoice
    invoice_id               UUID            NOT NULL REFERENCES invoices(id),

    -- Line item details
    description              VARCHAR(500)    NOT NULL,
    quantity                 INTEGER         NOT NULL CHECK (quantity > 0),
    unit_price_amount        NUMERIC(14, 2)  NOT NULL,
    unit_price_currency      VARCHAR(3)      NOT NULL DEFAULT 'USD',
    total_price_amount       NUMERIC(14, 2)  NOT NULL,
    total_price_currency     VARCHAR(3)      NOT NULL DEFAULT 'USD',

    -- Ordering
    line_number              INTEGER         NOT NULL,

    -- Audit
    created_at               TIMESTAMPTZ     NOT NULL DEFAULT NOW()
);

-- ---------------------------------------------------------------------------
-- Payments table — stores payment transaction records
-- ---------------------------------------------------------------------------
CREATE TABLE payments (
    id                       UUID            PRIMARY KEY,

    -- Reference to invoice
    invoice_id               UUID            NOT NULL REFERENCES invoices(id),

    -- Payment details
    amount                   NUMERIC(14, 2)  NOT NULL,
    currency                 VARCHAR(3)      NOT NULL DEFAULT 'USD',
    method                   VARCHAR(20)     NOT NULL,
    reference                VARCHAR(100)    NOT NULL,
    paid_at                  TIMESTAMPTZ     NOT NULL,

    -- Audit
    created_at               TIMESTAMPTZ     NOT NULL DEFAULT NOW()
);

-- ---------------------------------------------------------------------------
-- Ledger Entries table — double-entry bookkeeping records
-- ---------------------------------------------------------------------------
CREATE TABLE ledger_entries (
    id                       UUID            PRIMARY KEY DEFAULT gen_random_uuid(),

    -- Reference to invoice
    invoice_id               UUID            NOT NULL REFERENCES invoices(id),

    -- Ledger details
    entry_type               VARCHAR(20)     NOT NULL,
    debit_account            VARCHAR(50)     NOT NULL,
    credit_account           VARCHAR(50)     NOT NULL,
    amount                   NUMERIC(14, 2)  NOT NULL,
    currency                 VARCHAR(3)      NOT NULL DEFAULT 'USD',
    description              VARCHAR(500)    NOT NULL,

    -- Audit
    created_at               TIMESTAMPTZ     NOT NULL DEFAULT NOW()
);

-- ---------------------------------------------------------------------------
-- Indexes for common query patterns
-- ---------------------------------------------------------------------------

-- Invoice lookups by booking
CREATE INDEX idx_invoices_booking_id ON invoices (booking_id);

-- Invoice lookups by customer
CREATE INDEX idx_invoices_customer_id ON invoices (customer_id);

-- Status-based queries
CREATE INDEX idx_invoices_status ON invoices (status);

-- Due date queries (for overdue detection)
CREATE INDEX idx_invoices_due_date ON invoices (due_date);

-- Composite: customer + status
CREATE INDEX idx_invoices_customer_status ON invoices (customer_id, status);

-- Line items by invoice
CREATE INDEX idx_line_items_invoice_id ON line_items (invoice_id);

-- Payments by invoice
CREATE INDEX idx_payments_invoice_id ON payments (invoice_id);

-- Ledger entries by invoice
CREATE INDEX idx_ledger_entries_invoice_id ON ledger_entries (invoice_id);

-- Ledger entries by type
CREATE INDEX idx_ledger_entries_type ON ledger_entries (entry_type);

-- ---------------------------------------------------------------------------
-- Comments for documentation
-- ---------------------------------------------------------------------------
COMMENT ON TABLE invoices IS 'Invoice aggregate root — manages the full lifecycle of a billing invoice.';
COMMENT ON COLUMN invoices.id IS 'Domain-generated UUID serving as the aggregate identity.';
COMMENT ON COLUMN invoices.booking_id IS 'UUID of the booking this invoice is for.';
COMMENT ON COLUMN invoices.customer_id IS 'UUID of the customer being invoiced.';
COMMENT ON COLUMN invoices.status IS 'Current lifecycle state: DRAFT, ISSUED, PAID, OVERDUE, or CANCELLED.';
COMMENT ON COLUMN invoices.total_amount IS 'Total invoice amount (sum of all line items).';
COMMENT ON COLUMN invoices.due_date IS 'Payment due date.';

COMMENT ON TABLE line_items IS 'Individual charges on an invoice.';
COMMENT ON TABLE payments IS 'Payment transaction records against invoices.';
COMMENT ON TABLE ledger_entries IS 'Double-entry bookkeeping records for financial audit trail.';
