-- =============================================================================
-- V1__create_customer_tables.sql
-- FreightFlow Customer Service — Initial schema for the customer tables.
--
-- Creates the customers, contracts, customer_roles, and credit_history tables
-- with all columns required by the Customer aggregate root and related entities.
-- =============================================================================

-- ---------------------------------------------------------------------------
-- Customers table — stores the Customer aggregate root
-- ---------------------------------------------------------------------------
CREATE TABLE customers (
    -- Primary key: UUID generated by the application (domain-driven ID)
    id                          UUID            PRIMARY KEY,

    -- Customer profile
    company_name                VARCHAR(255)    NOT NULL,
    email                       VARCHAR(255)    NOT NULL UNIQUE,
    phone                       VARCHAR(50),

    -- Address (embedded value object)
    address_street              VARCHAR(255),
    address_city                VARCHAR(100),
    address_state               VARCHAR(100),
    address_postal_code         VARCHAR(20),
    address_country             VARCHAR(2),

    -- Classification
    customer_type               VARCHAR(30)     NOT NULL,
    status                      VARCHAR(20)     NOT NULL DEFAULT 'ACTIVE',

    -- Credit management
    credit_limit_amount         NUMERIC(15, 2)  NOT NULL DEFAULT 0.00,
    credit_limit_currency       VARCHAR(3)      NOT NULL DEFAULT 'USD',
    current_credit_used_amount  NUMERIC(15, 2)  NOT NULL DEFAULT 0.00,
    current_credit_used_currency VARCHAR(3)     NOT NULL DEFAULT 'USD',

    -- Timestamps
    registered_at               TIMESTAMPTZ     NOT NULL DEFAULT NOW(),
    created_at                  TIMESTAMPTZ     NOT NULL DEFAULT NOW(),
    updated_at                  TIMESTAMPTZ     NOT NULL DEFAULT NOW(),
    created_by                  VARCHAR(100),
    updated_by                  VARCHAR(100),

    -- Optimistic locking version
    version                     BIGINT          NOT NULL DEFAULT 0,

    -- Constraints
    CONSTRAINT chk_customer_type CHECK (customer_type IN ('SHIPPER', 'CONSIGNEE', 'FREIGHT_FORWARDER')),
    CONSTRAINT chk_customer_status CHECK (status IN ('ACTIVE', 'SUSPENDED', 'CLOSED')),
    CONSTRAINT chk_credit_limit_positive CHECK (credit_limit_amount >= 0),
    CONSTRAINT chk_credit_used_positive CHECK (current_credit_used_amount >= 0)
);

-- ---------------------------------------------------------------------------
-- Contracts table — stores customer contracts
-- ---------------------------------------------------------------------------
CREATE TABLE contracts (
    id                      UUID            PRIMARY KEY,
    customer_id             UUID            NOT NULL REFERENCES customers(id),
    contract_type           VARCHAR(20)     NOT NULL,
    discount_percentage     NUMERIC(5, 2)   NOT NULL DEFAULT 0.00,
    valid_from              DATE            NOT NULL,
    valid_to                DATE            NOT NULL,
    max_bookings_per_month  INTEGER         NOT NULL DEFAULT 100,
    created_at              TIMESTAMPTZ     NOT NULL DEFAULT NOW(),
    updated_at              TIMESTAMPTZ     NOT NULL DEFAULT NOW(),

    -- Constraints
    CONSTRAINT chk_contract_type CHECK (contract_type IN ('STANDARD', 'VOLUME', 'ENTERPRISE')),
    CONSTRAINT chk_discount_range CHECK (discount_percentage >= 0 AND discount_percentage <= 100),
    CONSTRAINT chk_valid_dates CHECK (valid_to > valid_from),
    CONSTRAINT chk_max_bookings_positive CHECK (max_bookings_per_month > 0)
);

-- ---------------------------------------------------------------------------
-- Customer roles table — RBAC roles for customer users
-- ---------------------------------------------------------------------------
CREATE TABLE customer_roles (
    id              UUID            PRIMARY KEY DEFAULT gen_random_uuid(),
    customer_id     UUID            NOT NULL REFERENCES customers(id),
    role_name       VARCHAR(50)     NOT NULL,
    assigned_at     TIMESTAMPTZ     NOT NULL DEFAULT NOW(),
    assigned_by     VARCHAR(100),

    -- Prevent duplicate role assignments
    CONSTRAINT uq_customer_role UNIQUE (customer_id, role_name)
);

-- ---------------------------------------------------------------------------
-- Credit history table — audit log for credit operations
-- ---------------------------------------------------------------------------
CREATE TABLE credit_history (
    id              UUID            PRIMARY KEY DEFAULT gen_random_uuid(),
    customer_id     UUID            NOT NULL REFERENCES customers(id),
    operation       VARCHAR(20)     NOT NULL,
    amount          NUMERIC(15, 2)  NOT NULL,
    currency        VARCHAR(3)      NOT NULL DEFAULT 'USD',
    balance_after   NUMERIC(15, 2)  NOT NULL,
    reference_id    VARCHAR(255),
    reference_type  VARCHAR(50),
    occurred_at     TIMESTAMPTZ     NOT NULL DEFAULT NOW(),
    description     VARCHAR(500),

    -- Constraints
    CONSTRAINT chk_credit_operation CHECK (operation IN ('ALLOCATE', 'RELEASE', 'ADJUST'))
);

-- ---------------------------------------------------------------------------
-- Indexes for common query patterns
-- ---------------------------------------------------------------------------

-- Customer email lookup (unique, already indexed by UNIQUE constraint)
-- Customer status queries
CREATE INDEX idx_customers_status ON customers (status);

-- Customer type queries
CREATE INDEX idx_customers_type ON customers (customer_type);

-- Composite index for type + status queries
CREATE INDEX idx_customers_type_status ON customers (customer_type, status);

-- Company name search (for LIKE queries)
CREATE INDEX idx_customers_company_name ON customers (LOWER(company_name));

-- Registration date ordering
CREATE INDEX idx_customers_registered_at ON customers (registered_at);

-- Contract lookups by customer
CREATE INDEX idx_contracts_customer_id ON contracts (customer_id);

-- Active contracts (date range)
CREATE INDEX idx_contracts_valid_dates ON contracts (valid_from, valid_to);

-- Credit history by customer
CREATE INDEX idx_credit_history_customer_id ON credit_history (customer_id);

-- Credit history by timestamp
CREATE INDEX idx_credit_history_occurred_at ON credit_history (occurred_at);

-- Customer roles by customer
CREATE INDEX idx_customer_roles_customer_id ON customer_roles (customer_id);

-- ---------------------------------------------------------------------------
-- Comments for documentation
-- ---------------------------------------------------------------------------
COMMENT ON TABLE customers IS 'Customer aggregate root — manages customer profiles, classification, and credit limits.';
COMMENT ON TABLE contracts IS 'Customer contracts defining pricing tiers, discounts, and booking limits.';
COMMENT ON TABLE customer_roles IS 'RBAC role assignments for customer users.';
COMMENT ON TABLE credit_history IS 'Audit log of all credit allocation and release operations.';
COMMENT ON COLUMN customers.id IS 'Domain-generated UUID serving as the aggregate identity.';
COMMENT ON COLUMN customers.company_name IS 'Legal company name of the customer.';
COMMENT ON COLUMN customers.email IS 'Primary contact email address (unique across all customers).';
COMMENT ON COLUMN customers.customer_type IS 'Classification: SHIPPER, CONSIGNEE, or FREIGHT_FORWARDER.';
COMMENT ON COLUMN customers.status IS 'Lifecycle state: ACTIVE, SUSPENDED, or CLOSED.';
COMMENT ON COLUMN customers.credit_limit_amount IS 'Maximum credit available for booking operations.';
COMMENT ON COLUMN customers.current_credit_used_amount IS 'Credit currently allocated to active bookings.';
COMMENT ON COLUMN customers.version IS 'Optimistic locking version — incremented on each update.';
COMMENT ON COLUMN contracts.discount_percentage IS 'Discount percentage applied to booking rates (0-100).';
COMMENT ON COLUMN contracts.max_bookings_per_month IS 'Maximum number of bookings allowed per calendar month.';
COMMENT ON COLUMN credit_history.operation IS 'Type of credit operation: ALLOCATE, RELEASE, or ADJUST.';
COMMENT ON COLUMN credit_history.reference_id IS 'ID of the entity that triggered this credit change (e.g., booking ID).';
