-- =============================================================================
-- V1__create_notification_tables.sql
-- FreightFlow Notification Service — Initial schema for notification tables.
--
-- Creates the notifications, templates, and delivery_log tables for
-- multi-channel notification management.
-- =============================================================================

-- ---------------------------------------------------------------------------
-- Notifications table — stores the Notification aggregate root
-- ---------------------------------------------------------------------------
CREATE TABLE notifications (
    -- Primary key: UUID generated by the application (domain-driven ID)
    id                  UUID            PRIMARY KEY,

    -- Recipient (customer or user ID)
    recipient_id        UUID            NOT NULL,

    -- Channel configuration
    channel_type        VARCHAR(20)     NOT NULL,
    channel_data        VARCHAR(2000)   NOT NULL,

    -- Content
    subject             VARCHAR(500)    NOT NULL,
    body                TEXT            NOT NULL,

    -- Delivery status
    status              VARCHAR(20)     NOT NULL DEFAULT 'PENDING',
    attempts            INTEGER         NOT NULL DEFAULT 0,
    sent_at             TIMESTAMPTZ,
    error               VARCHAR(2000),

    -- Audit columns
    created_at          TIMESTAMPTZ     NOT NULL DEFAULT NOW(),
    updated_at          TIMESTAMPTZ     NOT NULL DEFAULT NOW(),
    created_by          VARCHAR(100),
    updated_by          VARCHAR(100),

    -- Optimistic locking version
    version             BIGINT          NOT NULL DEFAULT 0,

    -- Constraints
    CONSTRAINT chk_notification_channel CHECK (channel_type IN ('EmailChannel', 'SmsChannel', 'WebhookChannel')),
    CONSTRAINT chk_notification_status CHECK (status IN ('PENDING', 'SENT', 'FAILED', 'RETRYING')),
    CONSTRAINT chk_notification_attempts CHECK (attempts >= 0)
);

-- ---------------------------------------------------------------------------
-- Templates table — stores notification templates for rendering
-- ---------------------------------------------------------------------------
CREATE TABLE templates (
    id              UUID            PRIMARY KEY DEFAULT gen_random_uuid(),
    name            VARCHAR(100)    NOT NULL UNIQUE,
    channel         VARCHAR(20)     NOT NULL,
    subject         VARCHAR(500)    NOT NULL,
    body_template   TEXT            NOT NULL,
    description     VARCHAR(500),
    is_active       BOOLEAN         NOT NULL DEFAULT true,
    created_at      TIMESTAMPTZ     NOT NULL DEFAULT NOW(),
    updated_at      TIMESTAMPTZ     NOT NULL DEFAULT NOW(),

    -- Constraints
    CONSTRAINT chk_template_channel CHECK (channel IN ('EMAIL', 'SMS', 'WEBHOOK'))
);

-- ---------------------------------------------------------------------------
-- Delivery log table — audit trail for all delivery attempts
-- ---------------------------------------------------------------------------
CREATE TABLE delivery_log (
    id                  UUID            PRIMARY KEY DEFAULT gen_random_uuid(),
    notification_id     UUID            NOT NULL REFERENCES notifications(id),
    attempt_number      INTEGER         NOT NULL,
    channel_type        VARCHAR(20)     NOT NULL,
    status              VARCHAR(20)     NOT NULL,
    sent_at             TIMESTAMPTZ     NOT NULL DEFAULT NOW(),
    response_code       INTEGER,
    response_body       VARCHAR(2000),
    error_message       VARCHAR(2000),
    duration_ms         BIGINT,

    -- Constraints
    CONSTRAINT chk_delivery_status CHECK (status IN ('SUCCESS', 'FAILED', 'TIMEOUT')),
    CONSTRAINT chk_attempt_positive CHECK (attempt_number > 0)
);

-- ---------------------------------------------------------------------------
-- Indexes for common query patterns
-- ---------------------------------------------------------------------------

-- Notification recipient lookup
CREATE INDEX idx_notifications_recipient_id ON notifications (recipient_id);

-- Status-based queries (e.g., find all PENDING for processing)
CREATE INDEX idx_notifications_status ON notifications (status);

-- Channel type queries
CREATE INDEX idx_notifications_channel_type ON notifications (channel_type);

-- Composite: status + channel for filtered processing
CREATE INDEX idx_notifications_status_channel ON notifications (status, channel_type);

-- Time-based queries (e.g., notifications dashboard)
CREATE INDEX idx_notifications_created_at ON notifications (created_at);

-- Retrying notifications ordered by last update (for retry scheduler)
CREATE INDEX idx_notifications_retrying ON notifications (status, updated_at) WHERE status = 'RETRYING';

-- Template lookups by name and channel
CREATE INDEX idx_templates_channel ON templates (channel);
CREATE INDEX idx_templates_active ON templates (is_active) WHERE is_active = true;

-- Delivery log by notification
CREATE INDEX idx_delivery_log_notification_id ON delivery_log (notification_id);

-- Delivery log by timestamp (for analytics)
CREATE INDEX idx_delivery_log_sent_at ON delivery_log (sent_at);

-- ---------------------------------------------------------------------------
-- Seed data: default notification templates
-- ---------------------------------------------------------------------------
INSERT INTO templates (name, channel, subject, body_template, description) VALUES
    ('booking-created-email', 'EMAIL',
     'FreightFlow — Booking Received [${bookingId}]',
     '<html><body><h2>Booking Received</h2><p>Dear ${customerName},</p><p>Your booking <strong>${bookingId}</strong> has been received and is pending confirmation.</p><p>Route: ${origin} → ${destination}</p><p>Thank you for choosing FreightFlow.</p></body></html>',
     'Email sent when a new booking is created'),

    ('booking-confirmed-email', 'EMAIL',
     'FreightFlow — Booking Confirmed [${bookingId}]',
     '<html><body><h2>Booking Confirmed</h2><p>Dear ${customerName},</p><p>Your booking <strong>${bookingId}</strong> has been confirmed and assigned to voyage <strong>${voyageId}</strong>.</p><p>Thank you for choosing FreightFlow.</p></body></html>',
     'Email sent when a booking is confirmed'),

    ('booking-cancelled-email', 'EMAIL',
     'FreightFlow — Booking Cancelled [${bookingId}]',
     '<html><body><h2>Booking Cancelled</h2><p>Dear ${customerName},</p><p>Your booking <strong>${bookingId}</strong> has been cancelled.</p><p>Reason: ${reason}</p><p>If you have questions, please contact support.</p></body></html>',
     'Email sent when a booking is cancelled'),

    ('invoice-generated-email', 'EMAIL',
     'FreightFlow — Invoice [${invoiceId}]',
     '<html><body><h2>Invoice Generated</h2><p>Dear ${customerName},</p><p>Invoice <strong>${invoiceId}</strong> has been generated for your booking.</p><p>Amount: ${amount} ${currency}</p><p>Due date: ${dueDate}</p></body></html>',
     'Email sent when an invoice is generated'),

    ('payment-received-email', 'EMAIL',
     'FreightFlow — Payment Receipt',
     '<html><body><h2>Payment Received</h2><p>Dear ${customerName},</p><p>We have received your payment of <strong>${amount} ${currency}</strong>.</p><p>Transaction ID: ${transactionId}</p><p>Thank you!</p></body></html>',
     'Email sent when a payment is received');

-- ---------------------------------------------------------------------------
-- Comments for documentation
-- ---------------------------------------------------------------------------
COMMENT ON TABLE notifications IS 'Notification aggregate root — manages multi-channel notification delivery and retry lifecycle.';
COMMENT ON TABLE templates IS 'Notification templates with Thymeleaf syntax for dynamic content rendering.';
COMMENT ON TABLE delivery_log IS 'Audit trail recording every delivery attempt with status and timing.';
COMMENT ON COLUMN notifications.id IS 'Domain-generated UUID serving as the aggregate identity.';
COMMENT ON COLUMN notifications.recipient_id IS 'UUID of the customer or user receiving the notification.';
COMMENT ON COLUMN notifications.channel_type IS 'Delivery channel: EmailChannel, SmsChannel, or WebhookChannel.';
COMMENT ON COLUMN notifications.channel_data IS 'JSON-serialized channel routing data (email address, phone number, or webhook URL).';
COMMENT ON COLUMN notifications.status IS 'Delivery state: PENDING, SENT, FAILED, or RETRYING.';
COMMENT ON COLUMN notifications.attempts IS 'Number of delivery attempts made (including retries).';
COMMENT ON COLUMN notifications.sent_at IS 'Timestamp when the notification was successfully delivered.';
COMMENT ON COLUMN notifications.error IS 'Last error message from a failed delivery attempt.';
COMMENT ON COLUMN notifications.version IS 'Optimistic locking version — incremented on each update.';
COMMENT ON COLUMN templates.body_template IS 'Thymeleaf template for rendering the notification body with variable substitution.';
COMMENT ON COLUMN delivery_log.duration_ms IS 'Time in milliseconds taken for the delivery attempt.';
