-- =============================================================================
-- V1__create_vessel_tables.sql
-- FreightFlow Vessel Schedule Service — Initial schema for fleet management.
--
-- Creates the vessels, voyages, port_calls, and routes tables.
-- =============================================================================

-- ---------------------------------------------------------------------------
-- Vessels table — stores the Vessel aggregate root
-- ---------------------------------------------------------------------------
CREATE TABLE vessels (
    -- Primary key: UUID generated by the application
    id                       UUID            PRIMARY KEY,

    -- Vessel identity
    name                     VARCHAR(100)    NOT NULL,
    imo_number               VARCHAR(20)     NOT NULL UNIQUE,
    flag                     VARCHAR(50)     NOT NULL,

    -- Capacity
    capacity_teu             INTEGER         NOT NULL CHECK (capacity_teu > 0),

    -- Status (ACTIVE, MAINTENANCE, RETIRED)
    status                   VARCHAR(20)     NOT NULL,

    -- Audit columns
    created_at               TIMESTAMPTZ     NOT NULL DEFAULT NOW(),
    updated_at               TIMESTAMPTZ     NOT NULL DEFAULT NOW(),

    -- Optimistic locking version
    version                  BIGINT          NOT NULL DEFAULT 0
);

-- ---------------------------------------------------------------------------
-- Voyages table — stores the Voyage aggregate root
-- ---------------------------------------------------------------------------
CREATE TABLE voyages (
    -- Primary key: UUID generated by the application
    id                       UUID            PRIMARY KEY,

    -- Vessel assigned to this voyage
    vessel_id                UUID            NOT NULL REFERENCES vessels(id),

    -- Voyage identity
    voyage_number            VARCHAR(30)     NOT NULL UNIQUE,

    -- Status (SCHEDULED, IN_TRANSIT, COMPLETED, CANCELLED)
    status                   VARCHAR(20)     NOT NULL,

    -- Capacity management
    total_capacity_teu       INTEGER         NOT NULL CHECK (total_capacity_teu > 0),
    remaining_capacity_teu   INTEGER         NOT NULL CHECK (remaining_capacity_teu >= 0),

    -- Audit columns
    created_at               TIMESTAMPTZ     NOT NULL DEFAULT NOW(),
    updated_at               TIMESTAMPTZ     NOT NULL DEFAULT NOW(),

    -- Optimistic locking version
    version                  BIGINT          NOT NULL DEFAULT 0,

    -- Constraint: remaining cannot exceed total
    CONSTRAINT chk_capacity CHECK (remaining_capacity_teu <= total_capacity_teu)
);

-- ---------------------------------------------------------------------------
-- Port Calls table — stores the scheduled stops in a voyage
-- ---------------------------------------------------------------------------
CREATE TABLE port_calls (
    id                       UUID            PRIMARY KEY DEFAULT gen_random_uuid(),

    -- Reference to voyage
    voyage_id                UUID            NOT NULL REFERENCES voyages(id),

    -- Port and schedule
    port                     VARCHAR(10)     NOT NULL,
    sequence_number          INTEGER         NOT NULL,
    estimated_arrival        TIMESTAMPTZ     NOT NULL,
    estimated_departure      TIMESTAMPTZ     NOT NULL,
    actual_arrival           TIMESTAMPTZ,
    actual_departure         TIMESTAMPTZ,

    -- Audit
    created_at               TIMESTAMPTZ     NOT NULL DEFAULT NOW(),

    -- Unique port call sequence within a voyage
    CONSTRAINT uq_voyage_port_sequence UNIQUE (voyage_id, sequence_number)
);

-- ---------------------------------------------------------------------------
-- Routes table — stores reusable route definitions
-- ---------------------------------------------------------------------------
CREATE TABLE routes (
    id                       UUID            PRIMARY KEY DEFAULT gen_random_uuid(),

    -- Route identity
    route_code               VARCHAR(20)     NOT NULL UNIQUE,
    name                     VARCHAR(200)    NOT NULL,

    -- Route endpoints
    origin_port              VARCHAR(10)     NOT NULL,
    destination_port         VARCHAR(10)     NOT NULL,

    -- Route metadata
    estimated_transit_days   INTEGER         NOT NULL CHECK (estimated_transit_days > 0),
    distance_nautical_miles  INTEGER,

    -- Status
    is_active                BOOLEAN         NOT NULL DEFAULT TRUE,

    -- Audit
    created_at               TIMESTAMPTZ     NOT NULL DEFAULT NOW(),
    updated_at               TIMESTAMPTZ     NOT NULL DEFAULT NOW()
);

-- ---------------------------------------------------------------------------
-- Indexes for common query patterns
-- ---------------------------------------------------------------------------

-- Vessel lookups
CREATE INDEX idx_vessels_status ON vessels (status);
CREATE INDEX idx_vessels_imo ON vessels (imo_number);
CREATE INDEX idx_vessels_flag ON vessels (flag);

-- Voyage lookups
CREATE INDEX idx_voyages_vessel_id ON voyages (vessel_id);
CREATE INDEX idx_voyages_status ON voyages (status);
CREATE INDEX idx_voyages_number ON voyages (voyage_number);
CREATE INDEX idx_voyages_capacity ON voyages (status, remaining_capacity_teu) WHERE status = 'SCHEDULED';

-- Port call lookups
CREATE INDEX idx_port_calls_voyage_id ON port_calls (voyage_id);
CREATE INDEX idx_port_calls_port ON port_calls (port);
CREATE INDEX idx_port_calls_arrival ON port_calls (estimated_arrival);

-- Route lookups
CREATE INDEX idx_routes_origin ON routes (origin_port);
CREATE INDEX idx_routes_destination ON routes (destination_port);
CREATE INDEX idx_routes_active ON routes (is_active) WHERE is_active = TRUE;

-- ---------------------------------------------------------------------------
-- Comments for documentation
-- ---------------------------------------------------------------------------
COMMENT ON TABLE vessels IS 'Vessel aggregate root — represents a container vessel in the fleet.';
COMMENT ON COLUMN vessels.imo_number IS 'International Maritime Organization identification number (unique).';
COMMENT ON COLUMN vessels.capacity_teu IS 'Maximum TEU (Twenty-foot Equivalent Unit) capacity of the vessel.';

COMMENT ON TABLE voyages IS 'Voyage aggregate root — represents a scheduled vessel sailing.';
COMMENT ON COLUMN voyages.voyage_number IS 'Unique voyage identifier (e.g., VYG-2024-001).';
COMMENT ON COLUMN voyages.total_capacity_teu IS 'Total TEU capacity allocated for this voyage.';
COMMENT ON COLUMN voyages.remaining_capacity_teu IS 'Remaining unreserved TEU capacity.';

COMMENT ON TABLE port_calls IS 'Scheduled port stops in a voyage itinerary.';
COMMENT ON COLUMN port_calls.port IS 'UN/LOCODE port code.';
COMMENT ON COLUMN port_calls.sequence_number IS 'Order of the port call in the voyage (1-based).';

COMMENT ON TABLE routes IS 'Reusable route definitions between port pairs.';
COMMENT ON COLUMN routes.route_code IS 'Unique route identifier (e.g., CNSHA-USLAX).';
