apiVersion: v1
kind: ServiceAccount
metadata:
  name: api-gateway
  namespace: freightflow
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: booking-service
  namespace: freightflow
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: tracking-service
  namespace: freightflow
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: billing-service
  namespace: freightflow
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: vessel-schedule-service
  namespace: freightflow
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: customer-service
  namespace: freightflow
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: notification-service
  namespace: freightflow
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: discovery-server
  namespace: freightflow
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: config-server
  namespace: freightflow
